apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: identityd
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: identityd
subjects:
- kind: ServiceAccount
  name: identityd
roleRef:
  kind: ClusterRole
  name: identityd
  apiGroup: rbac.authorization.k8s.io
