---
{ apiVersion: v1, kind: ServiceAccount, metadata: { name: athenz-identity-agent } }
---
{ apiVersion: v1, kind: ServiceAccount, metadata: { name: athenz-jwt-service } }
---
{ apiVersion: v1, kind: ServiceAccount, metadata: { name: athenz-initializer } }
---
{ apiVersion: v1, kind: ServiceAccount, metadata: { name: athenz-identityd } }
---
{ apiVersion: v1, kind: ServiceAccount, metadata: { name: mock-athenz } }

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata: { name: local-configmap-reader }
rules: [ { apiGroups: [""], resources: ["configmaps"], verbs: [ "get" ] } ]

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata: { name: local-secrets-reader }
rules: [ { apiGroups: [""], resources: ["secrets"], verbs: [ "get" ] } ]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata: { name: athenz-configmap-local }
roleRef:
  kind: Role
  name: local-configmap-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: system:serviceaccount:k8s-admin:athenz-initializer
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: system:serviceaccount:k8s-admin:athenz-identityd
  namespace: k8s-admin
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: system:serviceaccount:k8s-admin:athenz-identity-agent
  namespace: k8s-admin
  apiGroup: rbac.authorization.k8s.io


---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata: { name: athenz-secrets-local }
roleRef:
  kind: Role
  name: local-secrets-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: system:serviceaccount:k8s-admin:athenz-identityd
  namespace: k8s-admin
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: system:serviceaccount:k8s-admin:mock-athenz
  namespace: kube-system
  apiGroup: rbac.authorization.k8s.io

