---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata: { name: athenz-initializer }
rules: [ { apiGroups: [""], resources: ["pods"], verbs: [ "get", "list", "watch", "patch", "initialize" ] } ]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata: { name: athenz-initializer }
roleRef: { kind: ClusterRole, name: athenz-initializer, apiGroup: rbac.authorization.k8s.io }
subjects:
- kind: User
  name: system:serviceaccount:k8s-admin:athenz-initializer
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata: { name: athenz-identityd }
rules: [ { apiGroups: [""], resources: ["pods", "services"], verbs: [ "get", "list", "watch" ] } ]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: athenz-identityd
subjects:
- kind: User
  name: system:serviceaccount:k8s-admin:athenz-identityd
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: athenz-identityd
  apiGroup: rbac.authorization.k8s.io

