kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: local-reader
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: [ "get" ]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mock-athenz

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: athenz-initializer

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: athenz-initializer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: [ "get", "list", "watch", "patch", "initialize" ]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: athenz-initializer
subjects:
- kind: User
  name: system:serviceaccount:kube-system:athenz-initializer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: athenz-initializer
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: athenz-callback

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: athenz-callback
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: [ "get" ]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: athenz-callback
subjects:
- kind: User
  name: system:serviceaccount:kube-system:athenz-callback
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: athenz-callback
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: athenz-initializer-local
subjects:
- kind: User
  name: system:serviceaccount:kube-system:athenz-initializer
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: system:serviceaccount:kube-system:athenz-callback
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: system:serviceaccount:kube-system:mock-athenz
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: local-reader
  apiGroup: rbac.authorization.k8s.io


