#!/bin/bash

NS=kube-system

kubectl --namespace=default delete -f pods/test-app-pod.yaml

kubectl --namespace=${NS} delete -f initializer-configurations/athenz-initializer.yaml

kubectl --namespace=${NS} delete -f deployments/athenz-callback.yaml
kubectl --namespace=${NS} delete -f deployments/athenz-initializer.yaml
kubectl --namespace=${NS} delete -f deployments/mock-athenz.yaml

kubectl --namespace=${NS} delete -f configmaps/athenz-initializer.yaml
kubectl --namespace=${NS} delete -f rbac.yaml

kubectl --namespace=${NS} delete -f services/athenz-callback.yaml
kubectl --namespace=${NS} apply -f services/mock-athenz.yaml

kubectl --namespace=${NS} delete secret mock-athenz-root-ca
kubectl --namespace=${NS} delete secret athenz-initializer-identity
kubectl --namespace=${NS} delete secret athenz-initializer-public
kubectl --namespace=${NS} delete secret athenz-initializer-private

echo ====================================================================
echo "Remove the PEM files generated by initialize.sh for a clean slate!"
echo ====================================================================
