apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: athenz-test-app
  labels:
    app: athenz-test-app
spec:
  replicas: 1
  template:
    metadata:
      name: athenz-test-app
      annotations:
        initializer.kubernetes.io/athenz: "true"
      labels:
        app: athenz-test-app
    spec:
      serviceAccountName: athenz-test-app
      containers:
      - name: main
        image: local/k8s-athenz-test-app:latest
        imagePullPolicy: Never
        volumeMounts:
          - { name: ntoken,   mountPath: /tokens,         readOnly: true }
          - { name: tlscerts, mountPath: /var/athenz/tls, readOnly: true }
      volumes:
      - { name: ntoken, emptyDir: {} }
      - { name: tlscerts, emptyDir: {} }
