apiVersion: v1
kind: Pod
metadata:
  name: athenz-test-app
  annotations:
    initializer.kubernetes.io/athenz: "true"
  labels:
    app: athenz-test-app

spec:
  serviceAccountName: k8s-test-app
  containers:
  - name: main
    image: local/k8s-athenz-test-app:latest
    imagePullPolicy: Never
    volumeMounts:
      - { name: "ntoken", mountPath: "/tokens", readOnly: true }
      #- { name: "tlscerts", mountPath: "/var/athenz/tls", readOnly: true }
  volumes:
  - { name: ntoken, emptyDir: {} }
  #- { name: tlscerts, emptyDir: {} }
