apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: athenz-initializer
  labels:
    app: athenz-initializer
spec:
  replicas: 1 # must not be greater than 1 until HA is available
  template:
    metadata:
      initializers:
        pending: [] # does this work?
      labels:
        app: athenz-initializer
      name: athenz-initializer
    spec:
      serviceAccountName: athenz-initializer
      volumes:
      - { name: config-volume, configMap: { name: athenz-config } }
      containers:
      - name: main
        image: local/k8s-athenz-initializer:latest
        imagePullPolicy: Never
        volumeMounts:
        - { name: config-volume, mountPath: /var/cluster, readOnly: true}
        env:
        - { name: CONFIG_NAMESPACE, valueFrom: { fieldRef: { fieldPath: metadata.namespace } } }
        args:
        - "--config-map=athenz-initializer"
