apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mock-athenz
  labels:
    app: mock-athenz
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mock-athenz
      name: mock-athenz
    spec:
      serviceAccountName: mock-athenz
      volumes:
      - { name: "root-ca", secret: { secretName: "mock-athenz-root-ca" } }
      - { name: "tls", secret: { secretName: "mock-athenz-tls" } }

      containers:
      - name: main
        image: local/k8s-mock-athenz:latest
        imagePullPolicy: Never
        args:
        - "--auth-header=Athenz-Principal-Auth"
        - "--ca-listen=:4080"
        - "--cert=/var/athenz/server/server.cert"
        - "--dns-suffix=example.cloud"
        - "--key=/var/athenz/server/server.key"
        - "--listen=:4443"
        - "--root-ca-cert=/var/athenz/root-ca/cert"
        - "--root-ca-key=/var/athenz/root-ca/key"
        volumeMounts:
        - { name: "root-ca", mountPath: "/var/athenz/root-ca", readOnly: true }
        - { name: "tls", mountPath: "/var/athenz/server", readOnly: true }
